import { Inter } from 'next/font/google';
import { Metadata } from 'next';
import SignInForm from '../widgets/sign-in-form/sign-in-form';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create next App',
  description: 'Generated by create next app'
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
    <SignInForm />
        {children}
        </>
  );
}
