import './globals.css';
import { Inter } from 'next/font/google';
import { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create next App',
  description: 'Generated by create next app'
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
    {children}
</>
  );
}
